import SideBar from '@/components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from '@/components/SessionProvider'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import ClientProvider from '@/components/ClientProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Server components can be async functions, but clients cannot
  const session = await getServerSession(authOptions)
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {/* If session is available, proceed; else, bring up login component */}
          {!session ? (
            <Login />
          ): (
            <div className='flex'>
                {/* Sidebar */}
                <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto
                md:min-w-[20rem]'>
                  <SideBar />
                </div>

                {/* ClientProvider - Notification // React Hot Toast Notifs (Dynamic) */}
                <ClientProvider />


                <div className='bg-[#343541] flex-1'>{children}</div>
            </div>
          )}
          </SessionProvider>
        </body>
    </html>
  )
}
